"""empty message

Revision ID: 011f95f67212
Revises: aaf5ee6b27e6
Create Date: 2019-08-30 23:31:54.057211

"""

# revision identifiers, used by Alembic.
revision = '011f95f67212'
down_revision = 'aaf5ee6b27e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'chain_association_ibfk_1', 'chain_association', type_='foreignkey')
    op.drop_constraint(u'chain_association_ibfk_2', 'chain_association', type_='foreignkey')
    op.create_foreign_key(None, 'chain_association', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chain_association', 'chain', ['chain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chain_association', type_='foreignkey')
    op.drop_constraint(None, 'chain_association', type_='foreignkey')
    op.create_foreign_key(u'chain_association_ibfk_2', 'chain_association', 'chain', ['user_id'], ['id'])
    op.create_foreign_key(u'chain_association_ibfk_1', 'chain_association', 'user', ['chain_id'], ['id'])
    # ### end Alembic commands ###
