"""empty message

Revision ID: 141d53822b1f
Revises: b30bc6ae1a6c
Create Date: 2019-08-31 01:06:26.567220

"""

# revision identifiers, used by Alembic.
revision = '141d53822b1f'
down_revision = 'b30bc6ae1a6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain', sa.Column('eth_account', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chain', 'eth_account')
    # ### end Alembic commands ###
