"""empty message

Revision ID: 16b36011d1e9
Revises: 141d53822b1f
Create Date: 2019-08-31 01:07:41.482035

"""

# revision identifiers, used by Alembic.
revision = '16b36011d1e9'
down_revision = '141d53822b1f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain', sa.Column('chain_id', sa.String(length=255), nullable=True))
    op.drop_column('chain', 'eth_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain', sa.Column('eth_account', mysql.VARCHAR(collation=u'utf8mb4_general_ci', length=255), nullable=True))
    op.drop_column('chain', 'chain_id')
    # ### end Alembic commands ###
