"""empty message

Revision ID: 590a066a7439
Revises: 6b265af4eec4
Create Date: 2019-09-01 17:47:59.117126

"""

# revision identifiers, used by Alembic.
revision = '590a066a7439'
down_revision = '6b265af4eec4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
