"""empty message

Revision ID: 6b265af4eec4
Revises: b86cc85a26d8
Create Date: 2019-09-01 17:46:08.397184

"""

# revision identifiers, used by Alembic.
revision = '6b265af4eec4'
down_revision = 'b86cc85a26d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
