"""empty message

Revision ID: 762b50fcebc8
Revises: 16b36011d1e9
Create Date: 2019-08-31 01:10:07.926991

"""

# revision identifiers, used by Alembic.
revision = '762b50fcebc8'
down_revision = '16b36011d1e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
