"""empty message

Revision ID: 81e61a62e388
Revises: edeec327625d
Create Date: 2019-07-18 22:50:15.710137

"""

# revision identifiers, used by Alembic.
revision = '81e61a62e388'
down_revision = 'edeec327625d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
