"""empty message

Revision ID: aaf5ee6b27e6
Revises: c84d566b0b40
Create Date: 2019-08-30 01:18:06.583287

"""

# revision identifiers, used by Alembic.
revision = 'aaf5ee6b27e6'
down_revision = 'c84d566b0b40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_association',
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chain.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_association')
    op.drop_table('chain')
    # ### end Alembic commands ###
