"""empty message

Revision ID: b154f60e93a6
Revises: 762b50fcebc8
Create Date: 2019-09-01 14:00:34.682522

"""

# revision identifiers, used by Alembic.
revision = 'b154f60e93a6'
down_revision = '762b50fcebc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chain', ['chain_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chain', type_='unique')
    # ### end Alembic commands ###
