"""empty message

Revision ID: b30bc6ae1a6c
Revises: 011f95f67212
Create Date: 2019-08-31 01:03:21.086665

"""

# revision identifiers, used by Alembic.
revision = 'b30bc6ae1a6c'
down_revision = '011f95f67212'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
