"""empty message

Revision ID: b86cc85a26d8
Revises: b154f60e93a6
Create Date: 2019-09-01 14:13:00.909887

"""

# revision identifiers, used by Alembic.
revision = 'b86cc85a26d8'
down_revision = 'b154f60e93a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
